### ISSUE TITLE
Release Version 1.0.0

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Abiquo.Client#24]
**TODOs**
* [x] Execute integration tests
* [x] Verify that test VMs got cleaned up
* [x] Smoke test DLL in PoSH (i.e. Login test)
* [x] Create GitFlow release
* [x] Verify publishing to [NuGet.org](http://nuget.org/) via TeamCity succeeded
* [x] Verify that nuget shield is showing version
* [x] Close this issue
* [x] Close Milestone `1.0.0`

**Comment by rufer7** [comment]
This does not need to be an issue as we will release it anyway if we integrate

**Comment by rufer7** [comment]
All tests green

![image](https://cloud.githubusercontent.com/assets/5937292/18304535/26991ac2-74e3-11e6-86ae-a477467b537d.png)

**Comment by rufer7** [comment]
Done
