### ISSUE TITLE
Read polling Timeout and WaitTime from Custom Configuration Section

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Abiquo.Client#36]
Define default values of the following properties in a custom configuration section of the `App.config`

* `TaskPollingWaitTimeMilliseconds`
* `TaskPollingTimeoutMilliseconds` 

**TODOs**
* [ ] Define config section
* [ ] Read values from config section and assign to corresponding properties in constructor of `AbiquoClient`
* [ ] Adjust `.nuspec` file to copy `...dll.config` file

**HINT:** See [here](http://stackoverflow.com/questions/5304946/load-custom-configuration-sections-from-assembly-in-different-folder) if you have problems concerning loading custom configuration sections from different folder.
