### ISSUE TITLE
VM Operations

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Abiquo.Client#4]
Implement the following operations for `VMs`

**VM Operations**
* [x] Get `VirtualMachines`
* [x] Get `VirtualDataCenters`
* [x] Get `VirtualDataCenter` by Id
* [x] Get `VirtualApplicances`
* [x] Get `VirtualApplicance` by Id
* [x] Get `VirtualMachineTemplates`
* [x] Get `VirtualMachineTemplate` by Id
* [x] Get `DataCenterRepositories`
* [x] Get `DataCenterRepository` by Id
* [x] Create `VirtualMachine`
* [x] Delete `VirtualMachine`
* [x] Deploy `VirtualMachine`
* [x] Change state of a `VirtualMachine`
* [x] Modify/Update `VirtualMachine`

**Task/Job Operations**
* [x] Retrieve all Tasks of a `VirtualMachine`
* [x] Retrieve Task of a `VirtualMachine`

**General**
* [x] Implement link extraction
* [x] Implement link builder

**Comment by rufer7** [comment]
![image](https://cloud.githubusercontent.com/assets/5937292/17975845/8bf61796-6aeb-11e6-9b39-23472500f3a4.png)

**Comment by rufer7** [comment]
@dfch expects, that we do not need to wrap the disk operations for now

**Comment by rufer7** [comment]
Modify VirtualMachine returns empty response body. As passed by `Accept` header the expected reponse body type is `application/vnd.abiquo.acceptedrequest+json; version=3.8`

**Comment by rufer7** [comment]
The edit VM responses work as follow:

- If the VM is **deployed**, the response will be the task to track this action (202 with task)
- If the VM is **not deployed**, there is no task and no response will be retrieved (204).

**Comment by rufer7** [comment]
Support for different responses (204 with no content; 202 with task) in UpdateVirtualMachine operation implemented (see 64e6085550eabb8b195cb03781cb7e25fa315a25)
