### ISSUE TITLE
Get User Information

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Abiquo.Client#42]
Add methods to the client that allow to get user information. 

**TODOs**
* [x] Save user information, that gets returned on login (User object response of call to `~/login` endpoint)
  * [x] Create `CurrentUserInformation` property in `BaseAbiquoClient`
  * [x] Assert, that UserInformation property gets set on `Login()`
  * [x] Reset property on `Logout()`
* [x] `GetUserInformation()` method
  * [x] Ensure, that user is already logged in
  * [x] Return information about currently (Value of `CurrentUserInformation` property in `BaseAbiquoClient`)
* [x] `GetUserInformation(string username)` method
  * [x] Return user loaded via `~/enterprises/ID/users?has=USERNAME` (Result collection has to be filtered)
