### ISSUE TITLE
Method overloads for passing Object(s) instead of Id(s)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Abiquo.Client#46]
**TODOs**

Couple of methods defined in BaseAbiquoClient take multiple Id arguments. Usually we have objects like `VirtualDataCenter`, `VirtualAppliance`,.. we want to work with. State as is we need to extract the different Ids from the `self` or `edit` link. We would like to simplify that by adding method overloads that take objects and do the extraction.

See here for [development details](https://github.com/dfensgmbh/biz.dfch.CS.Abiquo.Client/wiki/Development)

* [x] Implement overloads that take objects, extract the Ids from the `self` or `edit` link for calling the corresponding method with Id parameters (See `SwitchEnterprise(Enterprise enterprise)` for an example)
  * [x] GetUsersWithRoles(Enterprise enterprise)
  * [x] GetUser(Enterprise enterprise, int id)
  * [x] GetDataCentersLimits(Enterprise enterprise)
  * [x] GetDataCentersLimits(Enterprise enterprise, int id)
  * [x] GetVirtualMachines(VirtualAppliance virtualAppliance)
  * [x] GetVirtualMachine(VirtualAppliance virtualAppliance, int id)
  * [x] CreateVirtualMachine(VirtualAppliance virtualAppliance, VirtualMachineTemplate virtualMachineTemplate)
  * [x] CreateVirtualMachine(VirtualAppliance virtualAppliance, VirtualMachineTemplate virtualMachineTemplate, VirtualMachine virtualMachine)
  * [x] DeployVirtualMachine(VirtualMachine virtualMachine, bool force)
  * [x] DeployVirtualMachine(VirtualMachine virtualMachine, bool force, bool waitForCompletion)
  * [x] UpdateVirtualMachine(VirtualMachine virtualMachine, bool force)
  * [x] UpdateVirtualMachine(VirtualMachine virtualMachine, bool force, bool waitForCompletion)
  * [x] ChangeStateOfVirtualMachine(VirtualMachine virtualMachine, VirtualMachineState state)
  * [x] ChangeStateOfVirtualMachine(VirtualMachine virtualMachine, VirtualMachineStateEnum state)
  * [x] ChangeStateOfVirtualMachine(VirtualMachine virtualMachine, VirtualMachineState state, bool waitForCompletion)
  * [x] ChangeStateOfVirtualMachine(VirtualMachine virtualMachine, VirtualMachineStateEnum state, bool waitForCompletion)
  * [x] DeleteVirtualMachine(VirtualMachine virtualMachine)
  * [x] DeleteVirtualMachine(VirtualMachine virtualMachine, bool force)
  * [x] GetNetworkConfigurationsForVm(VirtualMachine virtualMachine)
  * [x] GetNetworkConfigurationForVm(VirtualMachine virtualMachine, int id)
  * [x] GetNicsOfVirtualMachine(VirtualMachine virtualMachine)
  * [x] GetAllTasksOfVirtualMachine(VirtualMachine virtualMachine)
  * [x] GetTaskOfVirtualMachine(VirtualMachine virtualMachine, string taskId)
  * [x] GetVirtualMachineTemplates(DataCenterRepository dataCenterRepository)
  * [x] GetVirtualMachineTemplate(DataCenterRepository dataCenterRepository, int id)
  * [x] GetVirtualAppliances(VirtualDataCenter virtualDataCenter)
  * [x] GetVirtualAppliance(VirtualDataCenter virtualDataCenter, int id)
  * [x] GetDataCenterRepositories(Enterprise enterprise)
  * [x] GetDataCenterRepository(Enterprise enterprise, int id)
  * [x] GetPrivateNetworks(VirtualDataCenter virtualDataCenter)
  * [x] GetPrivateNetwork(VirtualDataCenter virtualDataCenter, int id)
  * [x] GetIpsOfPrivateNetwork(Vlan vlan, bool free)
  * [x] GetIpsOfExternalNetworkOfCurrentEnterprise(Vlan vlan, bool free)
  * [x] GetPublicNetworks(VirtualDataCenter virtualDataCenter)
  * [x] GetPublicNetwork(VirtualDataCenter virtualDataCenter, int id)
  * [x] GetPublicIpsToPurchaseOfPublicNetwork(VirtualDataCenter virtualDataCenter, VlanNetwork vlan)
  * [x] PurchasePublicIp(VirtualDataCenter virtualDataCenter, PublicIp publicIp);
  * [x] ReleasePublicIp(VirtualDataCenter virtualDataCenter, PublicIp publicIpid)

**Comment by rufer7** [comment]
resolved by #53
