### ISSUE TITLE
GetLinks by Type

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Abiquo.Client#48]
**TODOs**

* [x] Implement method on `AbiquoLinkBaseDto` for getting links by type
* [x] Rename `AbiquoMediaDataTypes` into `AbiquoVersionedMediaDataTypes`
* [x] Move types into separate class `AbiquoMediaDataTypes`
  * [x] Create class `AbiquoVersionedMediaDataTypes` with T4 template
* [x] Adjust GetLinksByType tests
