### ISSUE TITLE
Session Handling

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Abiquo.Client#51]
Implement session handling

**TODOs**
* [x] Read session token from Set-Cookie response header and save to session token on every request
* [x] Reset session token on logout
* [x] Add session cookie to request headers if present, otherwise add authorization header

**[OPTIONAL]**
* [ ] Add `KeepAlive` property
  * [ ] If set to `true`, start refresh mechanism (Load current user information)
  * [ ] If set to `false`, stop refresh mechanism

**Comment by rufer7** [comment]
Not needed anymore

**Comment by rufer7** [comment]
Optional tasks did not get implemented, as the actual use cases do not require keep alive feature.
